site_name: Distilled experience in Software Development
repo_name: sk0va/devbok
repo_url: https://github.com/sk0va/devbok
copyright: Copyright &copy; 2022 - 2023 sk0va

nav:
  - Disclaimer: disclaimer.md
  - Principles:
    - principles/Two types of applications.md
  - Development process:
    - Methodologies:
      - processes/scrum.md
    - For small team:
      - processes/For small team/GitFlow vs Trunk-based.md
      - processes/For small team/GtiFlow - Merge vs Rebase.md
  - Arcitecture:
    - Microservices:
      - architecture/Microservices/index.md
    - architecture/Clean Architecture.md
  - Design:
    - design/migrations.md
  - Implementation receipts:
    - db.md

theme:
  name: material
  palette:   
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

extra:
  version:
    provider: mike

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: sk0va
      repo: devbok
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets